version: '3.7'

services:

  db:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi_dev
    ports:
      - 27017:27017
    volumes:
      - db_dev_data:/data/db
    restart: always

  backend:
    container_name: strapi
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
    environment:
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - AUTHENTICATION_DATABASE=strapi_dev
      - CHOKIDAR_USEPOLLING=true
    #volumes:
      #- './backend/:/usr/src/app'
      #- '/usr/src/app/node_modules'
    ports:
      - 1337:1337
    depends_on:
      - db

  frontend:
    container_name: svelte
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    volumes:
      - './frontend/:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - "3000:3000"
      - "10000:10000"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  db_dev_data:
